[mgr]
cwd = { fg = "#f39660" }

hovered         = { reversed = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#e7c664", italic = true, underline = true }
find_position = { fg = "#b39df3", bg = "reset", italic = true }

marker_copied   = { fg = "#9ed072", bg = "#9ed072" }
marker_cut      = { fg = "#fc5d7c", bg = "#ff6077" }
marker_marked   = { fg = "#f39660", bg = "#f39660" }
marker_selected = { fg = "#e7c664", bg = "#e7c664" }

tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

count_copied   = { fg = "#2c2e34", bg = "#9ed072" }
count_cut      = { fg = "#2c2e34", bg = "#ff6077" }
count_selected = { fg = "#2c2e34", bg = "#e7c664" }

border_symbol = "│"
border_style  = { fg = "#7f8490" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#595f6f", bg = "#595f6f" }

mode_normal = { fg = "#2c2e34", bg = "#85d3f2" }
mode_select = { fg = "#2c2e34", bg = "#9ed072" }
mode_unset  = { fg = "#2c2e34", bg = "#e7c664" }

progress_label  = { fg = "#e2e2e3" }
progress_normal = { fg = "#76cce0", bg = "#595f6f" }
progress_error  = { fg = "#fc5d7c", bg = "#595f6f" }

permissions_t = { fg = "#76cce0" }
permissions_r = { fg = "#e7c664" }
permissions_w = { fg = "#fc5d7c" }
permissions_x = { fg = "#9ed072" }
permissions_s = { fg = "#7f8490" }

[select]
border   = { fg = "#76cce0" }
active   = { fg = "#b39df3" }
inactive = {}

[input]
border   = { fg = "#76cce0" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border = { fg = "#76cce0" }

[tasks]
border  = { fg = "#76cce0" }
title   = {}
hovered = { fg = "#b39df3", underline = true }

[which]
mask            = { bg = "#414550" }
cand            = { fg = "#f39660" }
rest            = { fg = "#7f8490" }
desc            = { fg = "#b39df3" }
separator       = "  "
separator_style = { fg = "#7f8490" }

[help]
on      = { fg = "#f39660" }
run     = { fg = "#b39df3" }
hovered = { reversed = true }
footer  = { fg = "#595f6f", bg = "#e7c664" }

[notify]
title_info  = { fg = "#9ed072" }
title_warn  = { fg = "#e7c664" }
title_error = { fg = "#fc5d7c" }

[filetype]

rules = [
  { name = "*", fg = "#e2e2e3" },
  { name = "*/", fg = "#85d3f2" }
]
